/**
 * Country code → flag emoji.
 * Uses regional indicator symbol pairs (Unicode).
 */
export function countryFlag(code: string): string {
  if (!code || code.length !== 2) return '🌍'
  const offset = 127397 // Regional indicator symbol offset
  return String.fromCodePoint(code.charCodeAt(0) + offset, code.charCodeAt(1) + offset)
}

/**
 * Country code → full name mapping for tooltip display.
 * Covers the most common countries in web analytics.
 */
export const COUNTRY_NAMES: Record<string, string> = {
  US: 'United States',
  CA: 'Canada',
  MX: 'Mexico',
  BR: 'Brazil',
  AR: 'Argentina',
  CO: 'Colombia',
  CL: 'Chile',
  PE: 'Peru',
  VE: 'Venezuela',
  EC: 'Ecuador',
  UY: 'Uruguay',
  PY: 'Paraguay',
  BO: 'Bolivia',
  PA: 'Panama',
  CR: 'Costa Rica',
  GT: 'Guatemala',
  HN: 'Honduras',
  SV: 'El Salvador',
  NI: 'Nicaragua',
  CU: 'Cuba',
  DO: 'Dominican Republic',
  PR: 'Puerto Rico',
  JM: 'Jamaica',
  TT: 'Trinidad & Tobago',
  GB: 'United Kingdom',
  DE: 'Germany',
  FR: 'France',
  ES: 'Spain',
  IT: 'Italy',
  NL: 'Netherlands',
  PT: 'Portugal',
  SE: 'Sweden',
  NO: 'Norway',
  FI: 'Finland',
  PL: 'Poland',
  CH: 'Switzerland',
  AT: 'Austria',
  BE: 'Belgium',
  DK: 'Denmark',
  IE: 'Ireland',
  CZ: 'Czechia',
  RO: 'Romania',
  GR: 'Greece',
  UA: 'Ukraine',
  HU: 'Hungary',
  BG: 'Bulgaria',
  HR: 'Croatia',
  RS: 'Serbia',
  SK: 'Slovakia',
  LT: 'Lithuania',
  LV: 'Latvia',
  EE: 'Estonia',
  SI: 'Slovenia',
  LU: 'Luxembourg',
  RU: 'Russia',
  CN: 'China',
  JP: 'Japan',
  KR: 'South Korea',
  IN: 'India',
  AU: 'Australia',
  NZ: 'New Zealand',
  ID: 'Indonesia',
  PH: 'Philippines',
  TH: 'Thailand',
  VN: 'Vietnam',
  MY: 'Malaysia',
  SG: 'Singapore',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  LK: 'Sri Lanka',
  MM: 'Myanmar',
  KH: 'Cambodia',
  LA: 'Laos',
  TW: 'Taiwan',
  HK: 'Hong Kong',
  MO: 'Macau',
  NP: 'Nepal',
  TR: 'Turkey',
  SA: 'Saudi Arabia',
  AE: 'UAE',
  IL: 'Israel',
  EG: 'Egypt',
  IQ: 'Iraq',
  IR: 'Iran',
  JO: 'Jordan',
  LB: 'Lebanon',
  KW: 'Kuwait',
  QA: 'Qatar',
  BH: 'Bahrain',
  OM: 'Oman',
  YE: 'Yemen',
  ZA: 'South Africa',
  NG: 'Nigeria',
  KE: 'Kenya',
  MA: 'Morocco',
  GH: 'Ghana',
  TZ: 'Tanzania',
  ET: 'Ethiopia',
  DZ: 'Algeria',
  TN: 'Tunisia',
  CI: 'Ivory Coast',
  SN: 'Senegal',
  CM: 'Cameroon',
  UG: 'Uganda',
  MZ: 'Mozambique',
  AO: 'Angola',
  MG: 'Madagascar',
  RW: 'Rwanda',
  ZW: 'Zimbabwe',
  NA: 'Namibia',
  BW: 'Botswana',
  IS: 'Iceland',
  GL: 'Greenland',
  MT: 'Malta',
  CY: 'Cyprus',
}
